POST http://localhost:8080/events
content-type: application/json
authorization: {{auth_token}}

{
  "name": "Test event 1",
  "description": "Test event",
  "location": "Test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}