POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjQ4ODg5MjMsInVzZXJJZCI6MX0.htvdi_aoOSpNvMi2ykq6fZkB8SZL577qL53kdNyme3s

{
  "name": "Test event",
  "description": "Test event",
  "location": "Test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}